// ============================================================
// Bank profiles — curated executive briefs (country → code → meta)
// Missing banks fall back to a generated sketch from live ST data.
// ============================================================

/**
 * @typedef {object} BankProfile
 * @property {string} [legalName]
 * @property {string} [shortName]
 * @property {string} [hq]
 * @property {string} [hqCity]
 * @property {string} [founded]
 * @property {string} [ownership]     // public / private / state / cooperative
 * @property {string} [controlling]   // controlling shareholder / group
 * @property {string[]} [shareholders]
 * @property {string} [originCountry] // ISO of parent / origin jurisdiction
 * @property {string} [originCountryName]
 * @property {number|null} [employeesInCountry]
 * @property {string} [employeesAsOf]
 * @property {string} [businessFocus]
 * @property {string} [history]       // 2–4 short sentences
 * @property {string} [context]       // competitive positioning
 * @property {{agency:string, rating:string, outlook?:string}[]} [ratings]
 * @property {string} [website]
 * @property {string} [irUrl]
 * @property {{title:string, url:string, source?:string, date?:string}[]} [news]
 * @property {{label?:string, url?:string}[]} [sources]
 */

/** @type {Record<string, Record<number, BankProfile>>} */
export const BANK_PROFILES = {
  chile: {
    1: {
      shortName: 'Banco de Chile',
      legalName: 'Banco de Chile',
      hq: 'Santiago',
      hqCity: 'Santiago',
      founded: '1893',
      ownership: 'Public (SSE: CHILE)',
      controlling: 'LQ Inversiones Financieras / Quiñenco–Citigroup structure',
      shareholders: ['LQ Inversiones Financieras', 'Citigroup (via joint control arrangements)', 'Free float'],
      originCountry: 'CL',
      originCountryName: 'Chile',
      businessFocus: 'Universal commercial bank: retail, SME, corporate and treasury',
      history: 'One of Chile’s oldest commercial banks. Combines a large retail franchise with corporate and treasury businesses. Part of the Quiñenco financial ecosystem with historical Citigroup ties.',
      context: 'Top-tier Chilean private bank by equity and loans; core competitor to Santander, BCI and Itaú.',
      website: 'https://www.bancochile.cl',
      irUrl: 'https://www.bancochile.cl',
      news: [
        { title: 'Banco de Chile — news search', url: 'https://news.google.com/search?q=Banco%20de%20Chile', source: 'Google News' },
      ],
    },
    59: {
      shortName: 'BTG Pactual Chile',
      legalName: 'Banco BTG Pactual Chile',
      hq: 'Santiago',
      hqCity: 'Santiago',
      founded: '2012 (banking license / BTG franchise in Chile)',
      ownership: 'Subsidiary of BTG Pactual',
      controlling: 'BTG Pactual',
      shareholders: ['BTG Pactual group'],
      originCountry: 'BR',
      originCountryName: 'Brazil',
      businessFocus: 'Corporate, investment-banking adjacency and wealth / private banking',
      history: 'Chilean commercial bank of the BTG Pactual group. Focuses on corporate, investment-banking adjacency and wealth / private banking rather than mass-market retail.',
      context: 'Niche franchise versus large Chilean universal banks. Origin country is Brazil.',
      website: 'https://www.btgpactual.cl',
      news: [
        { title: 'BTG Pactual Chile — news', url: 'https://news.google.com/search?q=BTG%20Pactual%20Chile%20banco', source: 'Google News' },
      ],
    },
    37: {
      shortName: 'Santander Chile',
      legalName: 'Banco Santander-Chile',
      hq: 'Santiago',
      hqCity: 'Santiago',
      founded: '1978 (Santander franchise in Chile)',
      ownership: 'Public subsidiary of Banco Santander (Spain)',
      controlling: 'Banco Santander S.A.',
      originCountry: 'ES',
      originCountryName: 'Spain',
      businessFocus: 'Universal bank: retail, consumer lending, SME, corporate and digital banking',
      history: 'Chilean unit of the Santander Group. Broad retail and corporate franchise with strong digital and consumer lending presence.',
      context: 'Usually among the largest private banks in Chile by assets and customers.',
      website: 'https://banco.santander.cl',
      news: [{ title: 'Santander Chile — news', url: 'https://news.google.com/search?q=Santander%20Chile%20banco', source: 'Google News' }],
    },
    16: {
      shortName: 'BCI',
      legalName: 'Banco de Crédito e Inversiones',
      hq: 'Santiago',
      hqCity: 'Santiago',
      founded: '1937',
      ownership: 'Public; Yarur family control structure',
      controlling: 'Yarur family / Empresas Juan Yarur',
      originCountry: 'CL',
      originCountryName: 'Chile',
      businessFocus: 'Universal bank: retail, commercial, corporate',
      history: 'Founded 1937 in Santiago. One of Chile’s major private banks; group also owns City National Bank of Florida.',
      context: 'Peer of Banco de Chile, Santander and Itaú among Chile’s large private banks.',
      website: 'https://www.bci.cl',
      news: [{ title: 'BCI — news', url: 'https://news.google.com/search?q=BCI%20banco%20Chile', source: 'Google News' }],
    },
    12: {
      shortName: 'BancoEstado',
      legalName: 'Banco del Estado de Chile',
      hq: 'Santiago',
      hqCity: 'Santiago',
      founded: '1953 as BancoEstado (roots 1855)',
      ownership: '100% Republic of Chile',
      controlling: 'Republic of Chile',
      originCountry: 'CL',
      originCountryName: 'Chile',
      businessFocus: 'Public universal bank: retail, mortgages, SME, government-related services',
      history: 'Chile’s only fully public commercial bank; created in 1953 from older state savings institutions dating to 1855.',
      context: 'Often among the largest Chilean banks by customers and geographic coverage.',
      website: 'https://www.bancoestado.cl',
      news: [{ title: 'BancoEstado — news', url: 'https://news.google.com/search?q=BancoEstado%20Chile', source: 'Google News' }],
    },
  },
  colombia: {
    66: {
      shortName: 'BTG Pactual Colombia',
      legalName: 'Banco BTG Pactual Colombia',
      hq: 'Bogotá',
      hqCity: 'Bogotá',
      ownership: 'Subsidiary of BTG Pactual',
      controlling: 'BTG Pactual',
      originCountry: 'BR',
      originCountryName: 'Brazil',
      businessFocus: 'Investment-banking led franchise expanded into commercial banking and wealth',
      history: 'Investment-banking led franchise of BTG Pactual in Colombia, expanded into commercial banking and wealth platforms.',
      context: 'Niche corporate / capital-markets oriented bank. Origin country is Brazil.',
      website: 'https://www.btgpactual.com.co',
      news: [{ title: 'BTG Pactual Colombia — news', url: 'https://news.google.com/search?q=BTG%20Pactual%20Colombia', source: 'Google News' }],
    },
    7: {
      shortName: 'Bancolombia',
      legalName: 'Bancolombia S.A.',
      hq: 'Medellín',
      hqCity: 'Medellín',
      founded: '1875 (as Banco de Colombia; Bancolombia after 1998 merger)',
      ownership: 'Public (BVC / NYSE: CIB ADR); Grupo Cibest holding',
      controlling: 'Grupo Cibest / historical Grupo Sura–Argos ecosystem influence',
      originCountry: 'CO',
      originCountryName: 'Colombia',
      employeesInCountry: 23600,
      employeesAsOf: '~2025 public figures',
      businessFocus: 'Universal bank: retail, SME, corporate, leasing, trust and Central American affiliates',
      history: 'Colombia’s largest bank by assets. Roots in Banco de Colombia (1875); 1998 merger created Bancolombia. HQ in Medellín.',
      context: 'Systemically important Colombian bank; primary peer set is Bogotá, Davivienda and Occidente.',
      website: 'https://www.bancolombia.com',
      irUrl: 'https://www.grupobancolombia.com/investor-relations',
      news: [{ title: 'Bancolombia — news', url: 'https://news.google.com/search?q=Bancolombia', source: 'Google News' }],
    },
    1: {
      shortName: 'Banco de Bogotá',
      legalName: 'Banco de Bogotá S.A.',
      hq: 'Bogotá',
      hqCity: 'Bogotá',
      founded: '1870',
      ownership: 'Public; controlled by Grupo Aval',
      controlling: 'Grupo Aval / Luis Carlos Sarmiento Angulo',
      originCountry: 'CO',
      originCountryName: 'Colombia',
      employeesInCountry: 15231,
      employeesAsOf: 'Sep 2025',
      businessFocus: 'Universal bank: commercial, consumer and mortgage lending',
      history: 'Colombia’s oldest commercial bank (1870). Flagship of Grupo Aval.',
      context: 'Core Aval bank; peers Bancolombia, Davivienda and Occidente.',
      website: 'https://www.bancodebogota.com',
      news: [{ title: 'Banco de Bogotá — news', url: 'https://news.google.com/search?q=Banco%20de%20Bogot%C3%A1', source: 'Google News' }],
    },
    39: {
      shortName: 'Davivienda',
      legalName: 'Banco Davivienda S.A.',
      hq: 'Bogotá',
      hqCity: 'Bogotá',
      founded: '1972',
      ownership: 'Controlled by Grupo Empresarial Bolívar',
      controlling: 'Grupo Empresarial Bolívar',
      originCountry: 'CO',
      originCountryName: 'Colombia',
      businessFocus: 'Universal bank: retail, mortgage heritage, SME, corporate; Central America',
      history: 'Started in 1972 as a savings-and-loan corporation; later Banco Davivienda under Grupo Empresarial Bolívar.',
      context: 'One of Colombia’s Big-Four banks.',
      website: 'https://www.davivienda.com',
      irUrl: 'https://ir.davivienda.com',
      news: [{ title: 'Davivienda — news', url: 'https://news.google.com/search?q=Davivienda', source: 'Google News' }],
    },
  },
  brasil: {
    1000080329: {
      shortName: 'Banco do Brasil',
      legalName: 'Banco do Brasil S.A.',
      hq: 'Brasília',
      hqCity: 'Brasília',
      founded: '1808',
      ownership: 'Mixed-economy public company (B3: BBAS3); Federal Government controlling shareholder (~50%)',
      controlling: 'União Federal (Brazilian Federal Government) — controlling shareholder with ~50% of capital',
      shareholders: [
        'União Federal (~50.0% — control)',
        'Free float (~49.6%)',
        'Treasury shares (~0.4%)',
      ],
      originCountry: 'BR',
      originCountryName: 'Brazil',
      employeesInCountry: 86574,
      employeesAsOf: '2024 (company disclosures)',
      businessFocus: 'Universal bank: retail, wholesale, agribusiness, government services, asset management, insurance and payments',
      history: 'Founded 12 October 1808 by Dom João VI — the oldest bank in continuous operation in Brazil. Mixed-economy listed company with the Federal Government as controlling shareholder. HQ in Brasília. Systemically important with a leading agribusiness credit franchise.',
      context: 'Typically among Brazil’s top banks by assets and equity with Itaú, Bradesco, Caixa and Santander.',
      website: 'https://www.bb.com.br',
      irUrl: 'https://ri.bb.com.br',
      news: [{ title: 'Banco do Brasil — news', url: 'https://news.google.com/search?q=Banco%20do%20Brasil%20BBAS3', source: 'Google News' }],
      sources: [
        { label: 'Banco do Brasil IR', url: 'https://ri.bb.com.br' },
        { label: 'Yahoo Finance profile', url: 'https://finance.yahoo.com/quote/BBAS3.SA/profile/' },
      ],
    },
    1000080336: {
      shortName: 'BTG Pactual',
      legalName: 'Banco BTG Pactual S.A.',
      hq: 'São Paulo',
      hqCity: 'São Paulo',
      founded: '1983',
      ownership: 'Public (B3: BPAC11)',
      controlling: 'Partnership / controlling group around founding partners',
      shareholders: ['Controlling partners', 'Free float (units BPAC11)'],
      originCountry: 'BR',
      originCountryName: 'Brazil',
      businessFocus: 'Investment bank + wealth/asset management with expanding commercial and digital retail banking',
      history: 'Leading Brazilian investment bank that expanded into wealth, asset management and commercial banking. Listed via units on B3.',
      context: 'Competes with Itaú BBA, XP and global bulge brackets in IB/wealth; growing retail digital franchise.',
      website: 'https://www.btgpactual.com',
      irUrl: 'https://ri.btgpactual.com',
      news: [{ title: 'BTG Pactual — news', url: 'https://news.google.com/search?q=BTG%20Pactual', source: 'Google News' }],
    },
    1000080099: {
      shortName: 'Itaú Unibanco',
      legalName: 'Itaú Unibanco Holding S.A.',
      hq: 'São Paulo',
      hqCity: 'São Paulo',
      founded: '2008 merger (Itaú 1945 / Unibanco 1924 roots)',
      ownership: 'Public (B3 / NYSE: ITUB); joint control via IUPAR / Itaúsa / Companhia E. Johnston',
      controlling: 'IUPAR / Itaúsa / Companhia E. Johnston — Villela/Setubal and Moreira Salles families',
      shareholders: ['IUPAR', 'Itaúsa S.A.', 'Companhia E. Johnston de Participações', 'Free float'],
      originCountry: 'BR',
      originCountryName: 'Brazil',
      employeesInCountry: 86228,
      employeesAsOf: 'Dec 2024 (Brazil workforce, Holding 6-K)',
      businessFocus: 'Universal bank: retail, SME, corporate & investment banking, asset management and insurance distribution',
      history: 'Largest private bank in Brazil after the Itaú–Unibanco merger. Universal bank with deep retail and wholesale franchises across LatAm. HQ in São Paulo.',
      context: 'Primary peer of Bradesco and Banco do Brasil in the Brazilian commercial banking oligopoly.',
      website: 'https://www.itau.com.br',
      irUrl: 'https://www.itau.com.br/relacoes-com-investidores',
      news: [{ title: 'Itaú Unibanco — news', url: 'https://news.google.com/search?q=Ita%C3%BA%20Unibanco', source: 'Google News' }],
    },
    1000080075: {
      shortName: 'Bradesco',
      legalName: 'Banco Bradesco S.A.',
      hq: 'Osasco (Cidade de Deus)',
      hqCity: 'Osasco',
      founded: '1943',
      ownership: 'Public (B3: BBDC3/BBDC4; NYSE: BBD)',
      controlling: 'Cidade de Deus / Fundação Bradesco-linked control structure',
      originCountry: 'BR',
      originCountryName: 'Brazil',
      employeesInCountry: 82095,
      employeesAsOf: 'Company disclosures (~2024–2025)',
      businessFocus: 'Universal bank with large insurance/pension franchise (Bradesco Seguros)',
      history: 'Founded 1943 by Amador Aguiar in Marília (SP). HQ in Cidade de Deus, Osasco. One of Brazil’s largest private banks.',
      context: 'Competes with Itaú and Banco do Brasil for mass retail and insurance distribution.',
      website: 'https://banco.bradesco',
      irUrl: 'https://www.bradescori.com.br',
      news: [{ title: 'Bradesco — news', url: 'https://news.google.com/search?q=Bradesco%20BBDC4', source: 'Google News' }],
    },
    1000080738: {
      shortName: 'Caixa Econômica Federal',
      legalName: 'Caixa Econômica Federal',
      hq: 'Brasília',
      hqCity: 'Brasília',
      founded: '1861',
      ownership: '100% Brazilian Federal Government',
      controlling: 'União Federal',
      originCountry: 'BR',
      originCountryName: 'Brazil',
      employeesInCountry: 86000,
      employeesAsOf: '~2021 public disclosures (order of magnitude)',
      businessFocus: 'Public universal bank: housing/FGTS, savings, social programs, lotteries, retail and SME',
      history: 'Founded 1861 by Emperor Pedro II. Largest fully government-owned bank in Latin America; core housing-finance and social-program channel.',
      context: 'Public-side peer of Banco do Brasil; largest mortgage/FGTS franchise.',
      website: 'https://www.caixa.gov.br',
      news: [{ title: 'Caixa — news', url: 'https://news.google.com/search?q=Caixa%20Econ%C3%B4mica%20Federal', source: 'Google News' }],
    },
    1000080185: {
      shortName: 'Santander Brasil',
      legalName: 'Banco Santander (Brasil) S.A.',
      hq: 'São Paulo',
      hqCity: 'São Paulo',
      founded: '1982 (Santander franchise in Brazil)',
      ownership: 'Public subsidiary of Banco Santander S.A. (Spain)',
      controlling: 'Banco Santander S.A. (Spain)',
      originCountry: 'ES',
      originCountryName: 'Spain',
      employeesInCountry: 49661,
      employeesAsOf: '2025 management report',
      businessFocus: 'Universal commercial bank: retail, consumer finance, SME, wholesale/CIB',
      history: 'Built scale in Brazil via acquisitions including Banespa. HQ in São Paulo. Largest Santander Group franchise outside Europe.',
      context: 'Fifth large Brazilian universal bank; Spanish origin.',
      website: 'https://www.santander.com.br',
      irUrl: 'https://www.santander.com.br/ri',
      news: [{ title: 'Santander Brasil — news', url: 'https://news.google.com/search?q=Santander%20Brasil%20banco', source: 'Google News' }],
    },
  },
  peru: {
    3: {
      shortName: 'BCP',
      legalName: 'Banco de Crédito del Perú',
      hq: 'Lima',
      hqCity: 'Lima',
      founded: '1889',
      ownership: 'Subsidiary of Credicorp',
      controlling: 'Credicorp Ltd.',
      originCountry: 'PE',
      originCountryName: 'Peru',
      businessFocus: 'Universal bank: nationwide retail and corporate; Credicorp flagship',
      history: 'Peru’s largest bank. Flagship of Credicorp with nationwide retail and corporate coverage.',
      context: 'Leads Peruvian banking by loans and deposits; peers include Interbank, BBVA Perú and Scotiabank Perú.',
      website: 'https://www.viabcp.com',
      irUrl: 'https://www.credicorp.com',
      news: [{ title: 'BCP / Credicorp — news', url: 'https://news.google.com/search?q=Banco%20de%20Cr%C3%A9dito%20del%20Per%C3%BA%20OR%20Credicorp', source: 'Google News' }],
    },
  },
  uruguay: {
    1: {
      shortName: 'BROU',
      legalName: 'Banco de la República Oriental del Uruguay',
      hq: 'Montevideo',
      hqCity: 'Montevideo',
      founded: '1896',
      ownership: 'State-owned',
      controlling: 'Oriental Republic of Uruguay',
      originCountry: 'UY',
      originCountryName: 'Uruguay',
      businessFocus: 'Public commercial bank: retail and government-related franchise',
      history: 'Uruguay’s largest bank and the main public commercial bank, with a broad retail and government-related franchise.',
      context: 'Systemically important; peers include Itaú Uruguay, Santander and Scotiabank.',
      website: 'https://www.brou.com.uy',
      news: [{ title: 'BROU — news', url: 'https://news.google.com/search?q=BROU%20banco%20Uruguay', source: 'Google News' }],
    },
    157: {
      shortName: 'HSBC Uruguay',
      legalName: 'HSBC Bank (Uruguay) S.A.',
      hq: 'Montevideo',
      hqCity: 'Montevideo',
      ownership: 'Subsidiary of HSBC Holdings (United Kingdom)',
      controlling: 'HSBC Holdings plc',
      originCountry: 'GB',
      originCountryName: 'United Kingdom',
      businessFocus: 'Commercial and retail banking under the HSBC brand',
      history: 'Uruguayan banking subsidiary of HSBC. UK-origin international bank.',
      context: 'Foreign-owned mid-size franchise versus BROU and regional peers.',
      website: 'https://www.hsbc.com.uy',
      news: [{ title: 'HSBC Uruguay — news', url: 'https://news.google.com/search?q=HSBC%20Uruguay', source: 'Google News' }],
    },
  },
  argentina: {
    // Galicia — code depends on BCRA catalog; soft-match by name in resolver
  },
  mexico: {
    12: {
      shortName: 'BBVA México',
      legalName: 'BBVA México, S.A.',
      hq: 'Mexico City',
      hqCity: 'Mexico City',
      ownership: 'Subsidiary of BBVA (Spain)',
      controlling: 'Banco Bilbao Vizcaya Argentaria, S.A.',
      originCountry: 'ES',
      originCountryName: 'Spain',
      businessFocus: 'Universal bank with deep retail penetration in Mexico',
      history: 'Largest bank in Mexico by many franchise metrics after the BBVA Bancomer integration. Universal bank with deep retail penetration.',
      context: 'Competes with Banorte, Santander México, Citibanamex and HSBC México.',
      website: 'https://www.bbva.mx',
      news: [{ title: 'BBVA México — news', url: 'https://news.google.com/search?q=BBVA%20M%C3%A9xico%20banco', source: 'Google News' }],
    },
    72: {
      shortName: 'Banorte',
      legalName: 'Banco Mercantil del Norte, S.A. (Banorte)',
      hq: 'Monterrey',
      hqCity: 'Monterrey',
      founded: '1899 (roots) / modern Banorte group',
      ownership: 'Public (BMV: GFNORTE)',
      controlling: 'Grupo Financiero Banorte',
      originCountry: 'MX',
      originCountryName: 'Mexico',
      businessFocus: 'Universal bank: retail, commercial, government and corporate',
      history: 'Leading Mexican-controlled universal bank; core of Grupo Financiero Banorte.',
      context: 'Primary Mexican-owned peer to BBVA México and Santander México.',
      website: 'https://www.banorte.com',
      irUrl: 'https://investors.banorte.com',
      news: [{ title: 'Banorte — news', url: 'https://news.google.com/search?q=Banorte', source: 'Google News' }],
    },
    // Nu México: operated as SOFIPO historically; CNBV authorized banca múltiple ~Jul 2026.
    // It will appear in LatamBanks only after the CNBV Boletín BM lists it as a bank.
  },
  panama: {
    108: {
      shortName: 'Banco de Occidente Panamá',
      legalName: 'Banco de Occidente (Panamá), S.A.',
      hq: 'Panama City',
      hqCity: 'Panama City',
      founded: '1982',
      ownership: 'Subsidiary of Banco de Occidente S.A. (Colombia) / Grupo Aval',
      controlling: 'Banco de Occidente S.A. (Cali) → Grupo Aval',
      shareholders: ['Banco de Occidente S.A. (Colombia)', 'Grupo Aval'],
      originCountry: 'CO',
      originCountryName: 'Colombia',
      businessFocus: 'International-license banking from Panama — corporate, trade and offshore-oriented services for non-resident clients',
      history: 'Opened 30 June 1982 under SBP International Banking License (Resolution 9-82). Subsidiary of Banco de Occidente (Cali) / Grupo Aval. HQ at Pacific Center, Paitilla, Panama City.',
      context: 'Panama international-license franchise of Colombian Banco de Occidente / Aval. Peer set is other LatAm international-license banks in Panama (Bogotá Int, Bancolombia Int, Davivienda Int).',
      website: 'https://bancoccidente.com.pa',
      news: [{ title: 'Banco de Occidente Panamá — news', url: 'https://news.google.com/search?q=Banco%20de%20Occidente%20Panam%C3%A1', source: 'Google News' }],
      sources: [
        { label: 'Banco de Occidente Panamá — Quiénes somos', url: 'https://bancoccidente.com.pa/bancodeoccidente-panama/quienes-somos.html' },
        { label: 'SBP', url: 'https://www.superbancos.gob.pa' },
      ],
    },
    76: {
      shortName: 'Banco de Bogotá Int.',
      legalName: 'Banco de Bogotá, S.A. (Licencia Internacional)',
      hq: 'Panama City',
      hqCity: 'Panama City',
      ownership: 'Subsidiary of Banco de Bogotá / Grupo Aval (Colombia)',
      controlling: 'Banco de Bogotá / Grupo Aval',
      shareholders: ['Grupo Aval'],
      originCountry: 'CO',
      originCountryName: 'Colombia',
      businessFocus: 'International-license banking from Panama',
      history: 'Panama international-license unit of Banco de Bogotá (Grupo Aval). Distinct from Banco de Bogotá’s general-license presence when both appear.',
      website: 'https://www.bancodebogota.com',
      news: [{ title: 'Banco de Bogotá Panamá — news', url: 'https://news.google.com/search?q=Banco%20de%20Bogot%C3%A1%20Panam%C3%A1', source: 'Google News' }],
    },
    75: {
      shortName: 'Bancolombia Panamá Int.',
      legalName: 'Bancolombia (Panamá), S.A.',
      hq: 'Panama City',
      hqCity: 'Panama City',
      ownership: 'Subsidiary of Bancolombia / Grupo Cibest (Colombia)',
      controlling: 'Bancolombia / Grupo Cibest',
      originCountry: 'CO',
      originCountryName: 'Colombia',
      businessFocus: 'International-license banking from Panama',
      history: 'Panama international-license franchise of Bancolombia.',
      website: 'https://www.bancolombia.com',
      news: [{ title: 'Bancolombia Panamá — news', url: 'https://news.google.com/search?q=Bancolombia%20Panam%C3%A1', source: 'Google News' }],
    },
    253: {
      shortName: 'Davivienda Internacional Panamá',
      legalName: 'Banco Davivienda Internacional (Panamá), S.A.',
      hq: 'Panama City',
      hqCity: 'Panama City',
      ownership: 'Subsidiary of Davivienda / Grupo Bolívar (Colombia)',
      controlling: 'Grupo Empresarial Bolívar',
      originCountry: 'CO',
      originCountryName: 'Colombia',
      businessFocus: 'International-license banking from Panama',
      history: 'Panama international-license unit of Davivienda.',
      website: 'https://www.davivienda.com',
      news: [{ title: 'Davivienda Internacional Panamá — news', url: 'https://news.google.com/search?q=Davivienda%20Internacional%20Panam%C3%A1', source: 'Google News' }],
    },
    72: {
      shortName: 'Itaú Panamá',
      legalName: 'Itaú (Panamá) S.A.',
      hq: 'Panama City',
      hqCity: 'Panama City',
      ownership: 'Subsidiary of Itaú Unibanco (Brazil)',
      controlling: 'Itaú Unibanco',
      originCountry: 'BR',
      originCountryName: 'Brazil',
      businessFocus: 'International-license banking from Panama',
      website: 'https://www.itau.com',
      news: [{ title: 'Itaú Panamá — news', url: 'https://news.google.com/search?q=Ita%C3%BA%20Panam%C3%A1%20banco', source: 'Google News' }],
    },
    79: {
      shortName: 'GNB Sudameris Bank',
      legalName: 'GNB Sudameris Bank, S.A.',
      hq: 'Panama City',
      hqCity: 'Panama City',
      ownership: 'Affiliate of GNB Sudameris / Gilinski group',
      controlling: 'Gilinski group / GNB Sudameris',
      originCountry: 'CO',
      originCountryName: 'Colombia',
      businessFocus: 'International-license banking from Panama',
      news: [{ title: 'GNB Sudameris Bank — news', url: 'https://news.google.com/search?q=GNB%20Sudameris%20Bank%20Panam%C3%A1', source: 'Google News' }],
    },
  },
  usa: {
    35154: {
      shortName: 'BTG Pactual Bank',
      legalName: 'BTG Pactual Bank, N.A.',
      hq: 'United States',
      hqCity: 'United States',
      founded: 'FDIC CERT 35154 (ex M.Y. Safra Bank, FSB; renamed ~Dec 2025)',
      ownership: 'Subsidiary of BTG Pactual',
      controlling: 'BTG Pactual',
      shareholders: ['BTG Pactual group'],
      originCountry: 'BR',
      originCountryName: 'Brazil',
      businessFocus: 'U.S. national bank supporting BTG’s U.S. banking franchise',
      history: 'U.S. national bank (FDIC CERT 35154). Formerly M.Y. Safra Bank, FSB; rebranded to BTG Pactual Bank, N.A. around December 2025. Distinct from Safra National Bank of New York (CERT 26876).',
      context: 'Small U.S. banking subsidiary of Brazilian BTG Pactual; equity is below the default FDIC top-300 cut, so LatamBanks pins CERT 35154 each quarter.',
      website: 'https://www.btgpactual.com',
      news: [
        { title: 'BTG Pactual Bank — news', url: 'https://news.google.com/search?q=BTG%20Pactual%20Bank%20NA%20OR%20%22M.Y.%20Safra%22', source: 'Google News' },
      ],
    },
  },
};

const NAME_ALIASES = [
  { country: 'argentina', re: /galicia/i, profile: {
    shortName: 'Banco Galicia',
    legalName: 'Banco de Galicia y Buenos Aires S.A.U.',
    hq: 'Buenos Aires, Argentina',
    ownership: 'Subsidiary of Grupo Financiero Galicia',
    controlling: 'Grupo Financiero Galicia',
    history: 'One of Argentina’s leading private banks with a large retail and SME franchise.',
    context: 'Peers include Santander Río, BBVA Argentina, Macro and Nación (public).',
    website: 'https://www.galicia.ar',
    news: [{ title: 'Banco Galicia — news', url: 'https://news.google.com/search?q=Banco%20Galicia%20Argentina', source: 'Google News' }],
  }},
  { country: 'usa', re: /jpmorgan|jp morgan|chase/i, profile: {
    shortName: 'JPMorgan Chase',
    legalName: 'JPMorgan Chase Bank, N.A.',
    hq: 'New York, USA',
    founded: '1799 / 2000 (Chase–JPM heritage)',
    ownership: 'Public (NYSE: JPM) — bank subsidiary of JPMorgan Chase & Co.',
    controlling: 'JPMorgan Chase & Co.',
    history: 'Largest U.S. bank by assets. Universal bank spanning consumer, commercial, markets and investment banking.',
    context: 'G-SIB; peers include Bank of America, Citibank and Wells Fargo.',
    website: 'https://www.jpmorganchase.com',
    irUrl: 'https://www.jpmorganchase.com/ir',
    news: [{ title: 'JPMorgan — news', url: 'https://news.google.com/search?q=JPMorgan%20Chase', source: 'Google News' }],
  }},
  { country: 'usa', re: /bank of america|bofa/i, profile: {
    shortName: 'Bank of America',
    legalName: 'Bank of America, N.A.',
    hq: 'Charlotte, USA',
    ownership: 'Public (NYSE: BAC)',
    controlling: 'Bank of America Corporation',
    history: 'One of the largest U.S. consumer and commercial banks, with a nationwide branch and digital franchise.',
    website: 'https://www.bankofamerica.com',
    irUrl: 'https://investor.bankofamerica.com',
    news: [{ title: 'Bank of America — news', url: 'https://news.google.com/search?q=Bank%20of%20America', source: 'Google News' }],
  }},
  { country: 'usa', re: /btg\s*pactual|m\.?\s*y\.?\s*safra/i, profile: {
    shortName: 'BTG Pactual Bank',
    legalName: 'BTG Pactual Bank, N.A.',
    hq: 'United States',
    founded: 'FDIC CERT 35154 (ex M.Y. Safra Bank, FSB)',
    ownership: 'Subsidiary of BTG Pactual',
    controlling: 'BTG Pactual',
    history: 'U.S. national bank of the BTG Pactual group (formerly M.Y. Safra Bank, FSB).',
    context: 'Pinned in the U.S. universe when equity is below the FDIC top-300 floor.',
    website: 'https://www.btgpactual.com',
    news: [{ title: 'BTG Pactual Bank — news', url: 'https://news.google.com/search?q=BTG%20Pactual%20Bank', source: 'Google News' }],
  }},
  { country: 'chile', re: /btg\s*pactual/i, profile: {
    shortName: 'BTG Pactual Chile',
    legalName: 'Banco BTG Pactual Chile',
    hq: 'Santiago, Chile',
    ownership: 'Subsidiary of BTG Pactual',
    controlling: 'BTG Pactual',
    history: 'Chilean banking unit of BTG Pactual, oriented to corporate and wealth clients.',
    context: 'Specialty franchise versus Chile’s large universal banks.',
    website: 'https://www.btgpactual.cl',
    news: [{ title: 'BTG Pactual Chile — news', url: 'https://news.google.com/search?q=BTG%20Pactual%20Chile', source: 'Google News' }],
  }},
];

/**
 * @param {string} countryKey
 * @param {number} code
 * @param {string} [displayName]
 * @returns {BankProfile}
 */
export function resolveBankProfile(countryKey, code, displayName = '') {
  const byCode = BANK_PROFILES[countryKey]?.[code];
  if (byCode) return { ...byCode, shortName: byCode.shortName || displayName };

  const name = displayName || '';
  for (const alias of NAME_ALIASES) {
    if (alias.country === countryKey && alias.re.test(name)) {
      return { ...alias.profile };
    }
  }

  const q = encodeURIComponent(name || `bank ${code}`);
  return {
    shortName: displayName || `Bank ${code}`,
    legalName: displayName || `Institution ${code}`,
    history: 'Curated narrative not yet loaded for this institution. Snapshot below uses supervisory figures already in LatamBanks.',
    context: 'Select peers in Bank Comparison to benchmark franchise size and profitability.',
    news: [
      { title: `Recent news — ${displayName || code}`, url: `https://news.google.com/search?q=${q}`, source: 'Google News' },
    ],
    website: undefined,
  };
}
